#!/usr/bin/env bats
# Tests for agentsync release.

load test_helper

# The version `release <bump>` writes from the seed's VERSION.
bumped() {
    local major minor patch
    IFS='.' read -r major minor patch <<< "$SEED_VERSION"
    case "$1" in
        major) echo "$((major + 1)).0.0" ;;
        minor) echo "$major.$((minor + 1)).0" ;;
        patch) echo "$major.$minor.$((patch + 1))" ;;
    esac
}

setup_file() {
    # Minimal engine seed (no .git): release only needs the CLI entry point,
    # its helpers, the three version files, and a CHANGELOG for the tag body.
    # Copying the whole repo and carrying its .git made each per-test clone race
    # under `bats --jobs` — the copied index disagreed with the freshly-written
    # working tree, so release's clean-tree check tripped intermittently.
    TEST_SEED="$(mktemp -d "${TMPDIR:-/tmp}/agentsync_release_seed.XXXXXX")"
    export TEST_SEED

    cp "$REPO_ROOT/VERSION" "$TEST_SEED/VERSION"
    read -r SEED_VERSION < "$TEST_SEED/VERSION"
    export SEED_VERSION
    printf '[package]\nname = "agentsync"\nversion = "%s"\nedition = "2024"\n\n[dependencies]\nclap = { version = "4.6", features = ["derive"] }\n' \
        "$SEED_VERSION" > "$TEST_SEED/Cargo.toml"
    printf '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "agentsync"\nversion = "%s"\ndependencies = [\n "clap",\n]\n\n[[package]]\nname = "clap"\nversion = "4.6.0"\n' \
        "$SEED_VERSION" > "$TEST_SEED/Cargo.lock"
    printf '# Changelog\n\n## %s\n\nA patch.\n\n- one fix\n\n## %s\n\nThe seed.\n' \
        "$(bumped patch)" "$SEED_VERSION" > "$TEST_SEED/CHANGELOG.md"
}

teardown_file() { teardown_seed_project; }

setup() {
    # Copy the static seed, then git-init fresh so the working tree is
    # deterministically clean: index stat info matches the just-written files,
    # leaving no room for a stale-index false positive in release's clean check.
    TEST_PROJECT="$(mktemp -d "${TMPDIR:-/tmp}/agentsync_clone.XXXXXX")"
    rmdir "$TEST_PROJECT"
    cp -c -R "$TEST_SEED" "$TEST_PROJECT" 2>/dev/null \
        || { rm -rf "$TEST_PROJECT"; cp -R "$TEST_SEED" "$TEST_PROJECT"; }
    cd "$TEST_PROJECT"
    git init --quiet
    git symbolic-ref HEAD refs/heads/main
    git config user.email "test@test.com"
    git config user.name "Test"
    git add -A
    git commit -m "seed" --quiet
}

teardown() {
    _rm_rf_resilient "$TEST_PROJECT.remote.git"
    teardown_test_project
}

@test "release patch bumps version" {
    echo "y" | "$AGENTSYNC_BIN" release patch --no-push
    local version
    read -r version < VERSION
    [ "$version" = "$(bumped patch)" ]
}

@test "release minor bumps version" {
    echo "y" | "$AGENTSYNC_BIN" release minor --no-push
    local version
    read -r version < VERSION
    [ "$version" = "$(bumped minor)" ]
}

@test "release major bumps version" {
    echo "y" | "$AGENTSYNC_BIN" release major --no-push
    local version
    read -r version < VERSION
    [ "$version" = "$(bumped major)" ]
}

@test "release bumps Cargo.toml and Cargo.lock with VERSION" {
    echo "y" | "$AGENTSYNC_BIN" release minor --no-push
    grep -qx "version = \"$(bumped minor)\"" Cargo.toml
    [ "$(grep -c '^version = ' Cargo.toml)" -eq 1 ]
    grep -q 'clap = { version = "4.6"' Cargo.toml
    awk '/^name = "agentsync"$/ { hit = 1; next } hit && /^version = / { print; exit }' Cargo.lock \
        | grep -qx "version = \"$(bumped minor)\""
    grep -qx 'version = 4' Cargo.lock
    grep -qx 'version = "4.6.0"' Cargo.lock
}

@test "release creates git tag" {
    echo "y" | "$AGENTSYNC_BIN" release patch --no-push
    git tag -l | grep -qx "$(bumped patch)"
}

@test "release tags with the CHANGELOG section of the new version" {
    echo "y" | "$AGENTSYNC_BIN" release patch --no-push
    local message
    message="$(git tag -l --format='%(contents)' "$(bumped patch)")"
    [ "$message" = "v$(bumped patch)

A patch.

- one fix" ]
}

@test "release creates commit" {
    echo "y" | "$AGENTSYNC_BIN" release patch --no-push
    git log --oneline -1 | grep -q "release: v$(bumped patch)"
}

@test "release commits VERSION, Cargo.toml, and Cargo.lock together" {
    echo "y" | "$AGENTSYNC_BIN" release patch --no-push
    [ "$(git show --format= --name-only HEAD | tr '\n' ' ')" = "Cargo.lock Cargo.toml VERSION " ]
    [ -z "$(git status --porcelain)" ]
}

@test "release default is patch" {
    echo "y" | "$AGENTSYNC_BIN" release --no-push
    local version
    read -r version < VERSION
    [ "$version" = "$(bumped patch)" ]
}

@test "release fails on dirty working tree" {
    echo "uncommitted" > dirty_file.txt
    run bash -c 'echo "y" | "$AGENTSYNC_BIN" release patch --no-push'
    [ "$status" -eq 1 ]
    [[ "$output" == *"not clean"* ]]
}

@test "release fails with unknown bump type" {
    run bash -c 'echo "y" | "$AGENTSYNC_BIN" release banana'
    [ "$status" -eq 1 ]
    [[ "$output" == *"Unknown bump type"* ]]
}

@test "release fails when Cargo.lock has no agentsync entry and writes nothing" {
    printf 'version = 4\n' > Cargo.lock
    git commit -qam "lock without agentsync"
    run bash -c 'echo "y" | "$AGENTSYNC_BIN" release patch --no-push'
    [ "$status" -eq 1 ]
    [[ "$output" == *"Cannot find the agentsync crate version in Cargo.lock"* ]]
    [[ "$output" != *"Continue?"* ]]
    local version
    read -r version < VERSION
    [ "$version" = "$SEED_VERSION" ]
    [ -z "$(git status --porcelain)" ]
}

@test "release fails without Cargo.toml" {
    git rm -q Cargo.toml
    git commit -qm "no manifest"
    run bash -c 'echo "y" | "$AGENTSYNC_BIN" release patch --no-push'
    [ "$status" -eq 1 ]
    [[ "$output" == *"Must be run from the AgentSync repository."* ]]
}

@test "release can be cancelled" {
    echo "n" | "$AGENTSYNC_BIN" release patch --no-push
    local version
    read -r version < VERSION
    [ "$version" = "$SEED_VERSION" ]
}

@test "release exits 1 at end of input on the prompt" {
    run "$AGENTSYNC_BIN" release patch --no-push < /dev/null
    [ "$status" -eq 1 ]
    [[ "$output" == *"Continue? [Y/n]: " ]]
    local version
    read -r version < VERSION
    [ "$version" = "$SEED_VERSION" ]
}

@test "release --no-push does not push" {
    run bash -c 'echo "y" | "$AGENTSYNC_BIN" release patch --no-push'
    [ "$status" -eq 0 ]
    [[ "$output" == *"local only"* ]]
    [[ "$output" == *"--no-push"* ]]
}

@test "release pushes main and the tag to origin" {
    git init --bare --quiet "$TEST_PROJECT.remote.git"
    git remote add origin "$TEST_PROJECT.remote.git"
    run bash -c 'echo "y" | "$AGENTSYNC_BIN" release patch'
    [ "$status" -eq 0 ]
    [[ "$output" == *"Pushing to origin..."* ]]
    [[ "$output" == *"Released v$(bumped patch)!"* ]]
    [ "$(git -C "$TEST_PROJECT.remote.git" log --format=%s -1 main)" = "release: v$(bumped patch)" ]
    git -C "$TEST_PROJECT.remote.git" tag -l | grep -qx "$(bumped patch)"
}

@test "release without an origin stops at the push with git's status" {
    run bash -c 'echo "y" | "$AGENTSYNC_BIN" release patch'
    [ "$status" -eq 128 ]
    [[ "$output" == *"Pushing to origin..."* ]]
    [[ "$output" != *"Released"* ]]
    git tag -l | grep -qx "$(bumped patch)"
}
