//! The managed `.gitignore` block of `lib/helpers/gitignore.sh`.

use std::collections::BTreeSet;
use std::io::Write;
use std::path::Path;

use crate::log::Log;
use crate::{Error, staging, text};

const START: &str = "# --- AI SYNC GENERATED START ---";
const END: &str = "# --- AI SYNC GENERATED END ---";

/// `gitignore_has_managed_block`.
pub fn has_managed_block(path: &Path) -> bool {
    std::fs::read(path).is_ok_and(|bytes| contains(&bytes, START))
}

fn contains(bytes: &[u8], marker: &str) -> bool {
    bytes
        .windows(marker.len())
        .any(|window| window == marker.as_bytes())
}

/// `update_gitignore`: replace the block between the markers, or append a
/// fresh one when either marker is missing.
pub fn update(path: &Path, paths: &[String], log: &mut Log) -> Result<(), Error> {
    let io = |e| Error::io(path, e);
    if !path.is_file() {
        std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(path)
            .map_err(io)?;
    }
    let mut block = format!(
        "{START}\n# Automatically generated by lib/sync.sh\n# Do not edit this block manually.\n"
    );
    let sorted: BTreeSet<&str> = paths
        .iter()
        .map(String::as_str)
        .filter(|p| !p.is_empty())
        .collect();
    for entry in sorted {
        block.push_str(entry);
        block.push('\n');
    }
    block.push_str(END);

    let current = std::fs::read(path).map_err(io)?;
    let (has_start, has_end) = (contains(&current, START), contains(&current, END));
    if has_start && has_end {
        let mut out = Vec::with_capacity(current.len() + block.len());
        let mut skip = false;
        for line in text::lines(&current) {
            if line == START.as_bytes() {
                out.extend_from_slice(block.as_bytes());
                out.push(b'\n');
                skip = true;
            } else if line == END.as_bytes() {
                skip = false;
            } else if !skip {
                out.extend_from_slice(line);
                out.push(b'\n');
            }
        }
        staging::write_beside(path, &out)?;
        log.step("Updated .gitignore block");
        return Ok(());
    }
    if has_start || has_end {
        log.warning("Detected inconsistent .gitignore markers. Appending a fresh generated block.");
    }
    std::fs::OpenOptions::new()
        .append(true)
        .open(path)
        .and_then(|mut file| file.write_all(format!("\n{block}\n").as_bytes()))
        .map_err(io)?;
    log.step("Added generated block to .gitignore");
    Ok(())
}

#[cfg(all(test, unix))]
mod tests {
    use super::*;

    fn paths(items: &[&str]) -> Vec<String> {
        items.iter().map(|p| p.to_string()).collect()
    }

    #[test]
    fn a_missing_file_gets_a_block_after_a_blank_line() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(".gitignore");
        let mut log = Log::default();
        update(
            &path,
            &paths(&[".cursor/", ".claude/", ".cursor/", "", "B/", "_x/", "b/"]),
            &mut log,
        )
        .unwrap();
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            "\n# --- AI SYNC GENERATED START ---\n# Automatically generated by lib/sync.sh\n# Do not edit this block manually.\n.claude/\n.cursor/\nB/\n_x/\nb/\n# --- AI SYNC GENERATED END ---\n"
        );
        assert_eq!(log.tail(1), ["   📁 Added generated block to .gitignore"]);
        assert!(has_managed_block(&path));
    }

    #[test]
    fn a_rerun_replaces_only_the_block_and_keeps_user_lines() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(".gitignore");
        std::fs::write(&path, "node_modules/\n").unwrap();
        let mut log = Log::default();
        update(&path, &paths(&[".claude/"]), &mut log).unwrap();
        std::fs::write(
            &path,
            format!("{}dist/", std::fs::read_to_string(&path).unwrap()),
        )
        .unwrap();
        update(&path, &[], &mut log).unwrap();
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            "node_modules/\n\n# --- AI SYNC GENERATED START ---\n# Automatically generated by lib/sync.sh\n# Do not edit this block manually.\n# --- AI SYNC GENERATED END ---\ndist/\n"
        );
        assert_eq!(log.tail(1), ["   📁 Updated .gitignore block"]);
    }

    #[test]
    fn a_lone_marker_appends_a_fresh_block_with_a_warning() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(".gitignore");
        std::fs::write(&path, "# --- AI SYNC GENERATED START ---\nx\n").unwrap();
        let mut log = Log::default();
        update(&path, &paths(&["y/"]), &mut log).unwrap();
        assert!(
            std::fs::read_to_string(&path)
                .unwrap()
                .ends_with("x\n\n# --- AI SYNC GENERATED START ---\n# Automatically generated by lib/sync.sh\n# Do not edit this block manually.\ny/\n# --- AI SYNC GENERATED END ---\n")
        );
        assert_eq!(
            log.tail(2),
            [
                "[WARNING] Detected inconsistent .gitignore markers. Appending a fresh generated block.",
                "   📁 Added generated block to .gitignore"
            ]
        );
    }
}
